[platformio]
default_envs = esp32-s3-devkitc-1
extra_configs =
    secrets.ini

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
monitor_filters = time, colorize

lib_deps =
    adafruit/Adafruit GFX Library@^1.12.3
    adafruit/Adafruit SSD1306@^2.5.15
    arduino-libraries/Arduino_JSON@^0.2.0